[phases.setup]
nixPkgs = ["php84", "php84Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache && /usr/local/bin/frankenphp php-server --listen :$PORT"
